--Farmacias
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'kdIWcB', '3536567339', '6 Moose Pass');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'YRE513291HGY', 'http://thetimes.co.uk', 9);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '86vQWs', '7553074355', '9 Schlimgen Avenue');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'IYF680980GWJ', 'http://multiply.com', 8);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'bU83DY', '3986675382', '418 Anhalt Trail');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'HDG408183GDC', 'http://hatena.ne.jp', 7);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'DOJJ2Z', '4040621905', '58722 Holy Cross Junction');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'KEB250797EAD', 'https://digg.com', 6);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'kJL3wU', '5488082022', '7362 Prairie Rose Street');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'ODD954730TYL', 'https://gov.uk', 5);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'ue8TfX', '8200956167', '14740 Butternut Court');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'XYY321300JXD', 'https://huffingtonpost.com', 1);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'hsBshv', '6469227620', '38312 Tony Way');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'FJR231893KBN', 'http://samsung.com', 2);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'fVDWZi', '3410257119', '6 Rusk Pass');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'OEW923231HJM', 'http://canalblog.com', 3);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'YykEcp', '1925397273', '370 Logan Lane');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'PXM329774AJP', 'http://yellowpages.com', 4);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'aLGU9E', '5928673344', '3387 Utah Park');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'NFS723987CJI', 'http://cdbaby.com', 10);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'WlDzei', '5665464035', '5354 Monterey Park');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'HBO146221FKN', 'http://domainmarket.com', 11);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'Lc11KS', '8329552723', '4042 Morningstar Way');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'CKE079726FCS', 'http://skype.com', 12);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'TNcrLK', '3631785367', '883 Londonderry Center');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'GHX707791QQZ', 'https://biblegateway.com', 13);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'bAxRUz', '2931632893', '17 Manufacturers Parkway');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'RSJ244854BWN', 'http://phoca.cz', 14);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'KW7ncM', '5876798867', '0035 Tennyson Lane');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'CUX695858XPQ', 'http://mediafire.com', 20);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'QfYG6b', '6922293262', '8 Forest Run Crossing');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'NSR704834YRU', 'https://hatena.ne.jp', 19);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '6XTF3K', '4975283661', '333 Miller Way');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'BQT906477UHY', 'http://cafepress.com', 18);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'T8oBlr', '1775097843', '24186 Independence Park');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'XHM762803YXT', 'https://usnews.com', 17);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'ICvWHL', '4489094300', '8 Reindahl Avenue');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'YAZ418936FFO', 'http://sourceforge.net', 16);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'MGIsXH', '6920942849', '5065 Shopko Plaza');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'USJ512673PCU', 'https://gmpg.org', 15);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '8LTDF5', '0606184430', '5 Old Shore Trail');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'KMT633935VJI', 'https://123-reg.co.uk', 21);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'RnhtfS', '2700834018', '1549 Schiller Road');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'KPA103984VZR', 'https://hhs.gov', 22);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'u7BVEi', '3602230589', '1 Jay Way');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'HDM307111EII', 'https://bloglines.com', 23);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'ruFohf', '1713697706', '1137 Stang Parkway');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'WWN425270PDV', 'http://hao123.com', 24);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'tNEBfF', '8245713336', '872 Porter Trail');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'VZG193335CDF', 'https://marketwatch.com', 40);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'QVuPzm', '9746611000', '15624 Moulton Place');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'GSP758977COI', 'https://foxnews.com', 39);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'Xe45vf', '1388452116', '886 Monica Avenue');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'RJS460818WMX', 'https://topsy.com', 38);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'FMxaWr', '9457567897', '96 Novick Alley');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'HWW898588NHU', 'http://rambler.ru', 37);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'Zfqsh7', '4107427622', '32354 Lukken Parkway');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'KIQ455508GYT', 'https://loc.gov', 36);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '9AuULF', '3186760788', '5028 Morningstar Junction');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'MEY112107MGX', 'https://about.me', 35);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '6xL5X5', '9084502204', '9 Dovetail Point');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'XJT443544AUP', 'http://livejournal.com', 25);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '0Flnm1', '3570575355', '8718 Elka Drive');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'DQI318625DNN', 'https://slashdot.org', 26);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'Q0oGdj', '2216243916', '2 Bobwhite Center');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'XVZ264732GLW', 'https://amazonaws.com', 27);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'pRCyIP', '7674845274', '4988 Florence Parkway');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'VLM891307VCM', 'https://bizjournals.com', 28);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'FsdB53', '9421141632', '7 Twin Pines Crossing');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'NAG761002GXP', 'https://exblog.jp', 29);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'goNEqI', '1817048276', '8 Mitchell Point');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'VYZ807858MKX', 'http://yahoo.co.jp', 30);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, '8MpQBX', '3359296449', '62 Lakeland Trail');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'VZC268756IJE', 'http://reuters.com', 34);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'QZGjN4', '1509438588', '49 Cordelia Point');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'DDJ845894LJI', 'http://wordpress.com', 33);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'EFA57r', '9736557644', '465 Canary Pass');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'QOC358006CIG', 'https://guardian.co.uk', 32);
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 1, 0, 0, 'BCptGc', '2478596017', '22695 Tony Drive');
insert into FARMACIA (centro_operaciones_id, rfc, pagina_web, gerente_id) values (centro_operaciones_seq.curval, 'EXJ510404TJJ', 'https://cyberchimps.com', 31);

--Oficinas
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'IjAYLN', '3348727841', '2 Aberg Plaza');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7461668806', 'ac nibh fusce lacus purus aliquet', 'Pacocha-Eichmann');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, '0TntAf', '0039771013', '55 Reindahl Junction');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4459646506', 'ultrices libero non mattis pulvinar', 'Howell, Abernathy and Trantow');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'HgxBOO', '7915681980', '16 Duke Circle');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9052398942', 'sit amet lobortis sapien sapien', 'Blanda and Sons');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'Fguyos', '1938256574', '23541 Bashford Point');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '1351853700', 'ut erat id mauris vulputate', 'Mraz, Towne and Funk');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, '5cTfJH', '5719560911', '8 Mandrake Circle');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '8136114203', 'semper porta volutpat quam pede lobortis', 'Nitzsche, Quigley and Ward');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'tS3N0W', '4631309321', '69 Granby Place');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7496708066', 'at dolor quis odio consequat', 'Farrell, Shanahan and Fadel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'hSmXvq', '2697422461', '72 Rieder Court');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5345675841', 'lobortis vel dapibus at diam', 'Altenwerth-Rempel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'TWUdug', '5020295638', '25 6th Court');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7713114939', 'eros viverra eget congue eget', 'Steuber Inc');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, '1qAZne', '8411400395', '48 Northland Circle');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4479971059', 'dis parturient montes nascetur ridiculus mus', 'Effertz, McLaughlin and Wilkinson');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'qPOkXR', '2074540651', '10 Manitowish Point');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6343130789', 'sed magna at nunc commodo', 'Herman-Windler');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'YX3bMt', '4263945286', '774 Elka Trail');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7147686967', 'adipiscing molestie hendrerit at vulputate', 'Bartoletti-Koelpin');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'RVBGhE', '9187068042', '4 Maple Plaza');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5387476702', 'sit amet eleifend pede libero quis', 'Kulas, Lynch and Nader');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'TVc1Cg', '3990748770', '3 Schurz Hill');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5544215334', 'eu sapien cursus vestibulum proin eu', 'Hyatt, Considine and Wunsch');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'dYrfsE', '7360339436', '55009 Annamark Center');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4525449778', 'sollicitudin ut suscipit a feugiat et', 'Marquardt LLC');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'eBeHEd', '5500828526', '62968 Troy Crossing');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5089136000', 'amet cursus id turpis integer aliquet', 'Brekke, Schuppe and Goyette');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'HQcEYl', '5056242168', '42117 Bultman Street');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9049041361', 'est congue elementum in hac habitasse', 'Towne, Bayer and Dibbert');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'lWjN2W', '1340017828', '5824 School Road');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2184256806', 'sit amet justo morbi ut odio', 'O''Connell Inc');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'oE994e', '1993459916', '5 Kings Street');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4759791875', 'sit amet turpis elementum ligula vehicula', 'Stroman Group');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'RJX7Md', '0818363257', '0433 Charing Cross Pass');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9885576196', 'accumsan tellus nisi eu orci mauris', 'Schuppe Group');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'pGixBG', '9574758040', '3 Eastwood Center');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2821049981', 'neque vestibulum eget vulputate ut ultrices', 'Hessel and Sons');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'UtCSQj', '5059288769', '6 Columbus Terrace');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2683112049', 'nec nisi vulputate nonummy maecenas', 'Mayer Inc');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'uCz2ob', '9129300226', '41721 Packers Plaza');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3066037948', 'in purus eu magna vulputate', 'Toy and Sons');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'Gk7kZG', '8090805099', '93 Cherokee Center');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5551889068', 'imperdiet et commodo vulputate justo in', 'Stehr, Kirlin and Denesik');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'hWnWjM', '8785411187', '263 Porter Parkway');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5088157750', 'habitasse platea dictumst aliquam augue', 'Green-Wehner');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'aPInOA', '7413368741', '99 Reindahl Point');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2483688001', 'magna vulputate luctus cum sociis', 'Mraz-Gerhold');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'HdPP59', '8973648657', '8 Lyons Hill');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2753141052', 'rutrum nulla tellus in sagittis dui', 'Barrows, Leuschke and Feil');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'ZXVcOQ', '8725586340', '603 Sheridan Crossing');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2641304379', 'mauris vulputate elementum nullam varius nulla', 'Bechtelar, Skiles and Jakubowski');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'VzqwoE', '0014945950', '63 Hanover Terrace');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5299113795', 'integer ac neque duis bibendum morbi', 'Barton Group');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'RRNBZH', '1586348604', '8 Northwestern Lane');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4559390811', 'gravida sem praesent id massa id', 'MacGyver Inc');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'QlEK8e', '9140584149', '25578 Fallview Place');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7379933436', 'lorem quisque ut erat curabitur', 'Padberg, Schuster and Kunde');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'WTB1rr', '4996484697', '6552 Fulton Park');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3537720315', 'leo rhoncus sed vestibulum sit', 'Christiansen LLC');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'Zw0MS8', '0139542483', '86 Michigan Hill');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9792028557', 'cras non velit nec nisi', 'O''Conner, Gottlieb and Keebler');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'UaUMgv', '6609099361', '04959 Steensland Junction');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '8836671517', 'nisl duis bibendum felis sed interdum', 'VonRueden LLC');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, '0D5DtM', '5693759581', '83409 Steensland Avenue');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6115336042', 'donec odio justo sollicitudin ut', 'Maggio, Wunsch and Mertz');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'mvjyiE', '2129412683', '4936 Loeprich Crossing');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3977128230', 'suspendisse ornare consequat lectus in est', 'Haley LLC');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, '8EhnMP', '7442081010', '54 Maple Wood Junction');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6072935335', 'purus sit amet nulla quisque', 'Keeling, Towne and Gusikowski');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'IkHjb9', '9656979629', '66 Sunbrook Road');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2465361945', 'duis bibendum felis sed interdum', 'Hammes, Feeney and Moore');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'p0dLIv', '3449264499', '944 Blaine Lane');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '1892711743', 'fusce congue diam id ornare', 'Wyman-Kuhlman');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'XKL1A8', '6551545175', '225 Cottonwood Drive');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7864544200', 'quam nec dui luctus rutrum', 'Flatley, Hammes and Weber');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 1, 0, 'Ipo7dm', '0657456404', '43462 Cottonwood Terrace');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5245801054', 'aliquam sit amet diam in', 'Breitenberg, Hahn and Eichmann');

--Almacenes
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'CHuuTK', '7728156020', '19 Fordem Alley');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 1, 'M', 'application/msword');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '6Y00S6', '6949876704', '89 Bobwhite Trail');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 2, 'M', 'application/x-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'dX5D2F', '9849320556', '54630 Crescent Oaks Terrace');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 3, 'D', 'application/x-mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'x4YkGh', '5094452318', '961 Armistice Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 4, 'D', 'application/msword');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'dgntuC', '8206927906', '6902 Petterle Center');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 5, 'M', 'application/powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '8ZOXGc', '9665278565', '8 Kenwood Alley');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 6, 'D', 'application/vnd.ms-powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'IVU9jq', '5625395986', '6 Cascade Hill');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 7, 'D', 'application/powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'zvTgB9', '1407662755', '92509 Maywood Street');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 8, 'D', 'application/powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '2hiM3f', '3747998114', '866 Holmberg Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 9, 'D', 'application/x-msexcel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'IOpnaY', '3689005623', '16 Shopko Circle');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 10, 'D', 'application/x-mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'KLVSt7', '6704499068', '74513 Becker Avenue');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 11, 'M', 'application/x-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'CwYPLH', '2251696203', '90 Mockingbird Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'otqPPr', '3442102444', '5587 Armistice Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 13, 'C', 'application/mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'Jleopb', '3364990524', '6429 Mcbride Crossing');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 14, 'D', 'application/powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'coLbie', '9196494983', '00183 Roxbury Junction');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 15, 'D', 'application/powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '7IGfiN', '0925388830', '00454 Bashford Crossing');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'AWwmGD', '3115139498', '63881 Harper Plaza');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 17, 'C', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'jyZnAI', '4171582426', '5927 Redwing Terrace');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 18, 'C', 'application/pdf');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'w4oelW', '8049808209', '352 Schurz Alley');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 19, 'M', 'application/vnd.ms-powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'WR0URC', '6580307204', '45597 Iowa Parkway');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'clIOvV', '0875929393', '1 Hintze Circle');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 21, 'D', 'application/pdf');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'KvmlLj', '5415498509', '00 Summit Park');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/pdf');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'Zhxjar', '3039592143', '2 East Avenue');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/x-msexcel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '91Q9Lo', '4773234064', '536 Coleman Terrace');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 24, 'D', 'application/pdf');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'SvUVVj', '0170283068', '51042 Merrick Alley');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 25, 'M', 'application/x-msexcel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '6Zt0xk', '8558686407', '82575 Nancy Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 26, 'D', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '8wDXMf', '7489575476', '1 Butterfield Center');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 27, 'D', 'application/msword');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'K7HjzP', '3734321344', '390 Loftsgordon Drive');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/vnd.ms-powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'lleTcd', '0916197729', '1361 Summer Ridge Pass');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 29, 'C', 'application/vnd.ms-powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'hDdWHW', '6203067518', '950 Heath Road');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'D', 'application/mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'cufd5L', '7176117715', '94682 Mallory Court');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 31, 'M', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'Zi60tT', '8802634926', '25605 Hollow Ridge Junction');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 32, 'C', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'oVk2JT', '8402161914', '0379 Eastwood Terrace');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 33, 'D', 'application/vnd.ms-powerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'xoq3ty', '6240705727', '2130 Continental Court');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 34, 'M', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'wyhuOQ', '9831202452', '7477 Gina Pass');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 35, 'C', 'application/pdf');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, '49r3t0', '4757705844', '086 Dunning Court');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 36, 'M', 'application/mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'I2vQ4M', '7858425699', '88261 Buhler Place');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 37, 'C', 'application/vnd.ms-excel');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'GAphzi', '6627005970', '2752 Summerview Parkway');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, null, 'M', 'application/msword');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'SqBnWy', '5742871815', '2 Eagle Crest Street');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 39, 'C', 'application/x-mspowerpoint');
insert into centro_operaciones (centro_operaciones_id, es_farmacia, es_oficina, es_almacen, clave, num_telefonico, direccion) values (centro_operaciones_seq.nextval, 0, 0, 1, 'bTIhHE', '0767625140', '7478 Dennis Circle');
insert into almacen (centro_operaciones_id, almacen_contingencia_id, tipo, documento) values (centro_operaciones_seq.curval, 40, 'M', 'application/pdf');