insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 69, 10, 30, 1);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 13, 7, 4, 2);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 90, 7, 33, 2);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 384, 8, 31, 3);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 196, 8, 5, 3);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 149, 15, 33, 4);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 242, 15, 10, 4);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 131, 18, 7, 5);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 247, 18, 33, 5);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 328, 18, 34, 5);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 28, 4, 10, 6);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 72, 4, 6, 6);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 227, 10, 26, 7);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 322, 10, 2, 7);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 344, 10, 6, 7);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 372, 9, 15,11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 69, 9, 38, 11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 171, 9, 3, 11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 301, 9, 35, 11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 488, 9, 6, 11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 48, 9, 40, 11);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 336,18, 3, 5);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 150, 18, 31, 5);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 300, 14, 35, 8);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 98, 14, 22, 8);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 374, 14, 7, 8);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 441, 14, 13, 8);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 480, 6, 14, 13);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 141, 6, 33, 13);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 240, 6, 24, 13);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 320, 19, 29, 16);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 318, 12, 5, 17);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 406, 18, 33, 18);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 163, 18, 39, 18);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 52, 14, 22, 19);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 286,14, 20, 19);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 373, 14, 12, 19);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 172,14, 2, 19);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 288, 14, 30, 19);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 148, 8, 31, 20);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 238, 8, 39, 20);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 123, 8, 30, 20);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 231, 8,1,20);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 235, 14,4,14);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 432, 14,5,14);
insert into FARMACIA_MEDICAMENTO (farmacia_medicamento_id, unidades_disponibles, medicamento_id, farmacia_id, presentacion_medicamento_id) values (farmacia_med_seq.nextval, 137, 9,20,11);