insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (1, 'LIDOCAINE HYDROCHLORIDE', 6);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (2, 'Ampicillin Sodium', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (3, 'Sodium Fluoride', 36);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (4, 'ACARBOSE', 21);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (5, 'Arsenicum alb', 26);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (6, 'hydrogen peroxide', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (7, 'Oxygen', 36);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (8, 'lisinopril', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (9, 'BuPROPion Hydrochloride', 35);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (10, 'Antacid and Antigas', 31);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (11, 'Oxycodone Hydrochloride', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (12, 'Guaifenesin', 31);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (13, 'Nicotine Polacrilex', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (14, 'ZINC OXIDE', 37);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (15, 'Sertraline Hydrochloride', 24);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (16, 'TITANIUM DIOXIDE', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (17, 'Metoprolol Tartrate', 25);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (18, 'Amlodipine Besylate', 22);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (19, 'Sodium Chloride', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (20, 'POLYETHYLENE GLYCOL 400L', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (21, 'Losartan Potassium', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (22, 'oxycodone hydrochloride', 20);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (23, 'Human Immunoglobulin G', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (24, 'Hydralazine Hydrochloride', 10);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (25, 'SULFACETAMIDE SODIUM, SULFUR', 9);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (26, 'Lorazepam', 6);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (27, 'Antihemophilic Factor (Recombinant)', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (28, 'Amoxicillin and Clavulanate Potassium', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (29, 'Arizona Cypress', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (30, 'Avobenzone', 35);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (31, 'Menthol', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (32, 'Influenza A Virus', 9);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (33, 'Venlafaxine Hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (34, 'Benzocaine, Resorcinol', 35);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (35, 'Almond', 30);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (36, 'NITROGLYCERIN', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (37, 'Cetylpyridinium chloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (38, 'amitriptyline hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (39, 'Sumatriptan', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (40, 'sarcobatus vermiculatus pollen', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (41, 'Bismuth', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (42, 'Enoxaparin sodium', 28);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (43, 'Menthol', 33);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (44, 'Hydrocortisone Silicone', 32);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (45, 'LAMOTRIGINE', 34);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (46, 'Dexamethasone', 25);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (47, 'Homosalate', 32);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (48, 'Indapamide', 24);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (49, 'Octinoxate and Titanium dioxide', 38);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (50, 'OCTINOXATE and OXYBENZONE', 17);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (51, 'Quetiapine fumarate', 26);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (52, 'CELECOXIB', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (53, 'tolterodine', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (54, 'PYRITHIONE ZINC', 7);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (55, 'levofloxacin', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (56, 'Triamcinolone Acetonide', 23);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (57, 'Ceftriaxone', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (58, 'Triclosan', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (59, 'Helianthemum', 32);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (60, 'Eucalyptol', 26);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (61, 'Anticoagulant', 39);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (62, 'Zonisamide', 27);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (63, 'Strawberry', 35);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (64, 'TRICLOSAN', 37);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (65, 'Fusarium oxysporum', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (66, 'Belinostat', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (67, 'OCTINOXATE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (68, 'Acetaminophen', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (69, 'OCTINOXATE', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (70, 'METHYL SALICYLATE', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (71, 'Captopril', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (72, 'Cetirizine Hydrochloride', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (73, 'Titanium Dioxide and Zinc oxide', 24);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (74, 'Benazepril Hydrochloride', 39);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (75, 'FOLIC ACID', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (76, 'Glycopyrrolate', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (77, 'Zinc Oxide', 24);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (78, 'Naproxen Sodium', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (79, 'Propranolol Hydrochloride', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (80, 'Dextran', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (81, 'Testes Apis', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (82, 'Antihemophilic Factor', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (83, 'PreNatal Vitamins Plus', 40);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (84, 'BENZALKONIUM CHLORIDE', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (85, 'DEXAMETHASONE SODIUM PHOSPHATE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (86, 'Loratadine', 34);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (87, 'Healing Ointment', 38);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (88, 'AVOBENZONE', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (89, 'pegvisomant', 20);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (90, 'Standardized Grass Pollen', 29);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (91, 'ARIPIPRAZOLE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (92, 'Echinacea', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (93, 'OCTINOXATE', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (94, 'Mountain Cedar', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (95, 'levothyroxine sodium', 26);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (96, 'Metformin hydrochloride', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (97, 'Allergenic Extracts Alum Precipitated', 40);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (98, 'losartan potassium', 32);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (99, 'paroxetine hydrochloride', 23);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (100, 'Stannous Fluoride', 11);
