--ENTRADA
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '13/11/2018', 'ENTRADA', 1, 1);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '10/09/2018', 'ENTRADA', 2, 2);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '20/03/2019', 'ENTRADA', 3, 3);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '05/01/2019', 'ENTRADA', 4, 4);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '09/01/2019', 'ENTRADA', 5, 5);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '26/07/2018', 'ENTRADA', 6, 6);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '21/12/2018', 'ENTRADA', 7, 7);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '13/03/2019', 'ENTRADA', 8, 8);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '06/08/2018', 'ENTRADA', 9, 9);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '10/07/2018', 'ENTRADA', 10, 10);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '12/12/2018', 'ENTRADA', 11, 11);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '01/10/2018', 'ENTRADA', 12, 12);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '06/05/2019', 'ENTRADA', 13, 13);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '26/10/2018', 'ENTRADA', 14, 14);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '05/04/2019', 'ENTRADA', 15, 15);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '08/10/2018', 'ENTRADA', 16, 16);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '25/05/2019', 'ENTRADA', 17, 17);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '20/08/2018', 'ENTRADA', 18, 18);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '01/04/2019', 'ENTRADA', 19, 19);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '08/10/2018', 'ENTRADA', 20, 20);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '03/02/2019', 'ENTRADA', 21, 21);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '06/06/2018', 'ENTRADA', 22, 22);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '18/10/2018', 'ENTRADA', 23, 23);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '30/01/2019', 'ENTRADA', 24, 24);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '05/12/2018', 'ENTRADA', 25, 25);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '17/08/2018', 'ENTRADA', 26, 26);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '17/03/2019', 'ENTRADA', 27, 27);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '14/11/2018', 'ENTRADA', 28, 28);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '22/11/2018', 'ENTRADA', 29, 29);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '13/09/2018', 'ENTRADA', 30, 30);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '14/01/2019', 'ENTRADA', 31, 31);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '21/11/2018', 'ENTRADA', 32, 32);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '28/08/2018', 'ENTRADA', 33, 33);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '17/05/2019', 'ENTRADA', 34, 34);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '30/06/2018', 'ENTRADA', 35, 35);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '12/05/2019', 'ENTRADA', 36, 36);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '19/04/2019', 'ENTRADA', 37, 37);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '15/10/2018', 'ENTRADA', 38, 38);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '16/12/2018', 'ENTRADA', 39, 39);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, '30/09/2018', 'ENTRADA', 40, 40);

--SALIDA
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 4, 4);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 8, 8);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 12, 12);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 16, 16);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 20, 20);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 24, 24);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 28, 28);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 32, 32);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 36, 36);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, centro_operaciones_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 40, 40);