--ENTRADA
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('13/11/2018','dd/mm/yyyy'), 'ENTRADA', 81, 1);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('10/09/2018','dd/mm/yyyy'), 'ENTRADA', 82, 2);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('20/03/2019','dd/mm/yyyy'), 'ENTRADA', 83, 3);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('05/01/2019','dd/mm/yyyy'), 'ENTRADA', 84, 4);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('09/01/2019','dd/mm/yyyy'), 'ENTRADA', 85, 5);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('26/07/2018','dd/mm/yyyy'), 'ENTRADA', 86, 6);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('21/12/2018','dd/mm/yyyy'), 'ENTRADA', 87, 7);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('13/03/2019','dd/mm/yyyy'), 'ENTRADA', 88, 8);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('06/08/2018','dd/mm/yyyy'), 'ENTRADA', 89, 9);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('10/07/2018','dd/mm/yyyy'), 'ENTRADA', 90, 10);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('12/12/2018','dd/mm/yyyy'), 'ENTRADA', 91, 11);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('01/10/2018','dd/mm/yyyy'), 'ENTRADA', 92, 12);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('06/05/2019','dd/mm/yyyy'), 'ENTRADA', 93, 13);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('26/10/2018','dd/mm/yyyy'), 'ENTRADA', 94, 14);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('05/04/2019','dd/mm/yyyy'), 'ENTRADA', 95, 15);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('08/10/2018','dd/mm/yyyy'), 'ENTRADA', 96, 16);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('25/05/2019','dd/mm/yyyy'), 'ENTRADA', 97, 17);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('20/08/2018','dd/mm/yyyy'), 'ENTRADA', 98, 18);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('01/04/2019','dd/mm/yyyy'), 'ENTRADA', 99, 19);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('08/10/2018','dd/mm/yyyy'), 'ENTRADA', 100, 20);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('03/02/2019','dd/mm/yyyy'), 'ENTRADA', 101, 21);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('06/06/2018','dd/mm/yyyy'), 'ENTRADA', 102, 22);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('18/10/2018','dd/mm/yyyy'), 'ENTRADA', 103, 23);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('30/01/2019','dd/mm/yyyy'), 'ENTRADA', 104, 24);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('05/12/2018','dd/mm/yyyy'), 'ENTRADA', 105, 25);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('17/08/2018','dd/mm/yyyy'), 'ENTRADA', 106, 26);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('17/03/2019','dd/mm/yyyy'), 'ENTRADA', 107, 27);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('14/11/2018','dd/mm/yyyy'), 'ENTRADA', 108, 28);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('22/11/2018','dd/mm/yyyy'), 'ENTRADA', 109, 29);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('13/09/2018','dd/mm/yyyy'), 'ENTRADA', 110, 30);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('14/01/2019','dd/mm/yyyy'), 'ENTRADA', 111, 31);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('21/11/2018','dd/mm/yyyy'), 'ENTRADA', 112, 32);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('28/08/2018','dd/mm/yyyy'), 'ENTRADA', 113, 33);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('17/05/2019','dd/mm/yyyy'), 'ENTRADA', 114, 34);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('30/06/2018','dd/mm/yyyy'), 'ENTRADA', 115, 35);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('12/05/2019','dd/mm/yyyy'), 'ENTRADA', 116, 36);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('19/04/2019','dd/mm/yyyy'), 'ENTRADA', 117, 37);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('15/10/2018','dd/mm/yyyy'), 'ENTRADA', 118, 38);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('16/12/2018','dd/mm/yyyy'), 'ENTRADA', 119, 39);
insert into operacion_almacen (operacion_almacen_id, fecha_evento, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, to_date('30/09/2018','dd/mm/yyyy'), 'ENTRADA', 120, 40);

--SALIDA
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 81, 4);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 82, 8);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 83, 12);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 110, 16);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 110, 20);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 110, 24);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 120, 28);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 97, 32);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 98, 36);
insert into operacion_almacen (operacion_almacen_id, tipo_evento, almacen_id, empleado_id) values (ope_almacen_seq.nextval, 'SALIDA', 99, 40);