insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 10, 'caja', '10');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 7, 'caja', '20');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 8, 'caja', '30');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 15, 'caja', '40');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 18, 'solución', '100ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 4, 'solución', '50ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 10, 'solución', '200ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 14,'ampolleta', '100ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 4, 'ampolleta', '50ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 10, 'caja', '30');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 9, 'caja', '30');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 11,'ampolleta', '500ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 6,'caja', '30');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 14, 'caja', '30');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 10, 'caja', '20');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 19,'ampolleta', '200ml');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 12,'caja', '20');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 18, 'caja', '20');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 14,'caja', '20');
insert into PRESENTACION_MEDICAMENTO (presentacion_medicamento_id, medicamento_id, presentacion, cantidad) values (presentacion_med_seq.nextval, 8,'caja', '20');
