insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (1, 'Tokley', 'Cruickshanks', 'LTDY930387', 'Tammara', '03/12/2009');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (2, 'Harmon', 'Spellecy', 'MROX135530', 'Olympie', '20/12/2010');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (3, 'McAughtrie', 'Bawden', 'CIVR569572', 'Cher', '10/03/2009');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (4, 'Scullion', 'Blamires', 'TGSR094824', 'Korrie', '16/04/2006');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (5, 'Hessle', 'Outridge', 'CGPK601065', 'Addy', '13/04/2010');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (6, 'Freschi', 'Sherebrooke', 'PFMW844826', 'Lucita', '08/06/2008');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (7, 'Kinde', 'Reeve', 'UXWH330918', 'Celisse', '30/03/2007');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (8, 'Wilkin', 'Bernardoni', 'XHHO067509', 'Elly', '27/06/2017');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (9, 'Caulkett', 'De Laspee', 'WNOH985962', 'Lucita', '11/10/2005');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (10, 'Penhalurick', 'Verni', 'IGJD492753', 'Tobin', '31/10/2017');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (11, 'Fairbridge', 'Mayall', 'JPZF205447', 'Heinrick', '15/08/2004');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (12, 'Reddy', 'Fechnie', 'LNHZ011224', 'Bessy', '28/06/2003');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (13, 'St. Leger', 'Kirke', 'XIPR550770', 'Trueman', '06/08/2000');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (14, 'Kernermann', 'Gilcrist', 'JUBC725325', 'Gina', '30/01/2003');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (15, 'Fortun', 'Dmitrievski', 'IRIX225858', 'Dorie', '14/11/2014');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (16, 'Dilger', 'Gell', 'YDJG790987', 'Jesus', '09/01/2007');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (17, 'Lartice', 'O''Kuddyhy', 'WVQD198094', 'Shamus', '22/02/2016');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (18, 'Chree', 'Guerrier', 'WQSY162203', 'Roseanna', '11/07/2008');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (19, 'Sember', 'Guillou', 'HZZS354638', 'York', '29/05/2003');
insert into empleado (empleado_id, apellido_paterno, apellido_materno, RFC, nombre, fecha_ingreso) values (20, 'Jovovic', 'McDonell', 'YVSK619437', 'Trixy', '31/03/2019');
