insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Mango Blossom', 'Infus drotrecogin alfa');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Ensulizole, Octinoxate, Octisalate, Oxybenzone, and Titanium dioxide', 'Incision of testes');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Benzocaine', 'IVUS peripheral vessels');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'CLEMATIS RECTA FLOWERING TOP', 'GI scan & isotope funct');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chlorpheniramine Maleate', 'Excis perianal skin tag');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chloroxylenol', 'Lacrimal sys dx proc NEC');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chloroxylenol', 'Occlude abd vein NEC');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'temazepam', 'Opn chest cardiac massag');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'amoxicillin and clavulanate potassium', 'Foot & toe arthroscopy');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Doxycycline Hyclate', 'Lap incis hern repr-grft');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'HEPARIN SODIUM', 'Thoracic vessel excision');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Isopropyl Alcohol', 'Remov biliary/liver tube');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Corn Smut', 'C & s-female genital');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Olanzapine', 'Parasitology-eye');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Piperonyl butoxide, Pyrethrum extract', 'Uterine suspension NEC');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Ibuprofen', 'Imp crtd sinus stm,totl');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Quetiapine fumarate', 'Gastric repair NEC');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Menthol', 'Local destr ova les NEC');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Melatonin, Nadidum, Niacin, Pyridoxinum hydrochloricum, Zincum sulphuricum, Hypothalamus, Lithium carbonicum, Magnesia carbonica, Pineal, Pituitary,', 'C & s-endocrine');
insert into Medicamento (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chlorpheniramine Maleate', 'Lap biopsy of ovary');
