insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Mango Blossom', 'Infus');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Ensulizole', 'Octinoxate');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Benzocaine', 'IVUS');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'CLEMATIS RECTA', 'GI scan');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chlorpheniramine Maleate', 'Excis perianal');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chloroxylenol', 'Lacrimal sys dx proc NEC');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chloroxylenol', 'Occlude abd vein NEC');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'temazepam', 'Opn chest');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'amoxicillin and', 'Foot ');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Doxycycline Hyclate', 'Lap incis hern');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'HEPARIN SODIUM', 'Thoracic vessel excision');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Isopropyl Alcohol', 'Remov biliary liver tube');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Corn Smut', 'female genital');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Olanzapine', 'Parasitologyeye');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Piperonyl butoxide', 'Uterine suspension');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Ibuprofen', 'Imp crtd sinus');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Quetiapine fumarate', 'Gastric repair NEC');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Menthol', 'Local destr ova les NEC');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Melatonin', 'Cendocrine');
insert into MEDICAMENTO (medicamento_id, sustancia_activa, descripcion) values (medicamento_seq.nextval, 'Chlorpheniramine Maleate', 'Lap biopsy of ovary');
