insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'LIDOCAINE HYDROCHLORIDE', 6);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Ampicillin Sodium', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Sodium Fluoride', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'ACARBOSE', 20);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Arsenicum alb', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'hydrogen peroxide', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Oxygen', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'lisinopril', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'BuPROPion Hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Antacid and Antigas', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Oxycodone Hydrochloride', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Guaifenesin', 20);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Nicotine Polacrilex', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'ZINC OXIDE', 17);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Sertraline Hydrochloride', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'TITANIUM DIOXIDE', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Metoprolol Tartrate', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Amlodipine Besylate', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Sodium Chloride', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'POLYETHYLENE GLYCOL 400L', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Losartan Potassium', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'oxycodone hydrochloride', 20);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Human Immunoglobulin G', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Hydralazine Hydrochloride', 10);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'SULFACETAMIDE SODIUM, SULFUR', 9);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Lorazepam', 6);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Antihemophilic ', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Amoxicillin ', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Arizona Cypress', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Avobenzone', 13);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Menthol', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Influenza A Virus', 9);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Venlafaxine Hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Benzocaine, Resorcinol', 13);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Almond', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'NITROGLYCERIN', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Cetylpyridinium ', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'amitriptyline hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Sumatriptan', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'sarcobatus vermiculatus pollen', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Bismuth', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Enoxaparin sodium', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Menthol', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Hydrocortisone Silicone', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'LAMOTRIGINE', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Dexamethasone', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Homosalate', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Indapamide', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Octinoxate ', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'OCTINOXATE and OXYBENZONE', 17);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Quetiapine fumarate', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'CELECOXIB', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'tolterodine', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'PYRITHIONE ZINC', 7);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'levofloxacin', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Triamcinolone Acetonide', 13);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Ceftriaxone', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Triclosan', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Helianthemum', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Eucalyptol', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Anticoagulant', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Zonisamide', 17);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Strawberry', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'TRICLOSAN', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Fusarium oxysporum', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Belinostat', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'OCTINOXATE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Acetaminophen', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'OCTINOXATE', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'METHYL SALICYLATE', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Captopril', 12);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Cetirizine Hydrochloride', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Titanium Dioxid', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Benazepril Hydrochloride', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'FOLIC ACID', 8);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Glycopyrrolate', 15);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Zinc Oxide', 14);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Naproxen Sodium', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Propranolol Hydrochloride', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Dextran', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Testes Apis', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Antihemophilic Factor', 1);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'PreNatal Vitamins Plus', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'BENZALKONIUM CHLORIDE', 11);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'DEXAMETHASONE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Loratadine', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Healing Ointment', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'AVOBENZONE', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'pegvisomant', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Standardized Grass Pollen', 2);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'ARIPIPRAZOLE', 18);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Echinacea', 19);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'OCTINOXATE', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Mountain Cedar', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'levothyroxine sodium', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Metformin hydrochloride', 16);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Allergenic Extracts', 4);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'losartan potassium', 3);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'paroxetine hydrochloride', 5);
insert into NOMBRE_MEDICAMENTO (nombre_medicamento_id, nombre, medicamento_id) values (nombre_med_seq.nextval, 'Stannous Fluoride', 20);
