insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7461668806', 'ac nibh fusce lacus purus aliquet', 'Pacocha-Eichmann');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4459646506', 'ultrices libero non mattis pulvinar', 'Howell, Abernathy and Trantow');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9052398942', 'sit amet lobortis sapien sapien', 'Blanda and Sons');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '1351853700', 'ut erat id mauris vulputate', 'Mraz, Towne and Funk');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '8136114203', 'semper porta volutpat quam pede lobortis', 'Nitzsche, Quigley and Ward');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7496708066', 'at dolor quis odio consequat', 'Farrell, Shanahan and Fadel');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5345675841', 'lobortis vel dapibus at diam', 'Altenwerth-Rempel');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7713114939', 'eros viverra eget congue eget', 'Steuber Inc');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4479971059', 'dis parturient montes nascetur ridiculus mus', 'Effertz, McLaughlin and Wilkinson');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6343130789', 'sed magna at nunc commodo', 'Herman-Windler');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7147686967', 'adipiscing molestie hendrerit at vulputate', 'Bartoletti-Koelpin');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5387476702', 'sit amet eleifend pede libero quis', 'Kulas, Lynch and Nader');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5544215334', 'eu sapien cursus vestibulum proin eu', 'Hyatt, Considine and Wunsch');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4525449778', 'sollicitudin ut suscipit a feugiat et', 'Marquardt LLC');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5089136000', 'amet cursus id turpis integer aliquet', 'Brekke, Schuppe and Goyette');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9049041361', 'est congue elementum in hac habitasse', 'Towne, Bayer and Dibbert');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2184256806', 'sit amet justo morbi ut odio', 'O''Connell Inc');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4759791875', 'sit amet turpis elementum ligula vehicula', 'Stroman Group');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9885576196', 'accumsan tellus nisi eu orci mauris', 'Schuppe Group');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2821049981', 'neque vestibulum eget vulputate ut ultrices', 'Hessel and Sons');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2683112049', 'nec nisi vulputate nonummy maecenas', 'Mayer Inc');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3066037948', 'in purus eu magna vulputate', 'Toy and Sons');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5551889068', 'imperdiet et commodo vulputate justo in', 'Stehr, Kirlin and Denesik');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5088157750', 'habitasse platea dictumst aliquam augue', 'Green-Wehner');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2483688001', 'magna vulputate luctus cum sociis', 'Mraz-Gerhold');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2753141052', 'rutrum nulla tellus in sagittis dui', 'Barrows, Leuschke and Feil');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2641304379', 'mauris vulputate elementum nullam varius nulla', 'Bechtelar, Skiles and Jakubowski');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5299113795', 'integer ac neque duis bibendum morbi', 'Barton Group');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '4559390811', 'gravida sem praesent id massa id', 'MacGyver Inc');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7379933436', 'lorem quisque ut erat curabitur', 'Padberg, Schuster and Kunde');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3537720315', 'leo rhoncus sed vestibulum sit', 'Christiansen LLC');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '9792028557', 'cras non velit nec nisi', 'O''Conner, Gottlieb and Keebler');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '8836671517', 'nisl duis bibendum felis sed interdum', 'VonRueden LLC');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6115336042', 'donec odio justo sollicitudin ut', 'Maggio, Wunsch and Mertz');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '3977128230', 'suspendisse ornare consequat lectus in est', 'Haley LLC');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '6072935335', 'purus sit amet nulla quisque', 'Keeling, Towne and Gusikowski');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '2465361945', 'duis bibendum felis sed interdum', 'Hammes, Feeney and Moore');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '1892711743', 'fusce congue diam id ornare', 'Wyman-Kuhlman');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '7864544200', 'quam nec dui luctus rutrum', 'Flatley, Hammes and Weber');
insert into OFICINA (centro_operaciones_id, call_center, clave, nombre) values (centro_operaciones_seq.curval, '5245801054', 'aliquam sit amet diam in', 'Breitenberg, Hahn and Eichmann');
